### ISSUE TITLE
Error when generating paqr_kapac virtual environment

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/PAQR_KAPAC#1]
I tried the command:

`conda create -n paqr_kapac -c bioconda -c ostrokach --file requirements_py3.txt`

And I get the following error message:

> Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - r-essentials==1.4.3
>   - r-optparse==1.3.2
> Use "conda info <package>" to see the dependencies for each package.

**Comment by koljaLanger** [comment]
Hey Foivos,
Thanks für reporting. I'll have a look.
Ralf

Foivos Gypas <notifications@github.com> schrieb am Di., 17. Juli 2018,
15:23:

**Comment by koljaLanger** [comment]
Hi Foivos

I updated the requirements_py3.txt file and also made some changes in the
README. I did two commits in the original directory which is:
/scicore/home/zavolan/GROUP/PolyA/manuscripts/manuscript_KAPAC/PAQR_KAPAC_sourceCode

Unfortunately, and for god knows whatever reason, I am not allowed to push
to remote anymore. Maybe, the problem here is that when I set up the
repository, I did it on the scicore gitlab. Later, I added a second remote
which was the publiczavolan. Even later, we changed the publiczavolan into
an organization. Maybe git is now confused because to the scicore git I
have to push as schmiral and to the publiczavolan as koljaLanger.
Can you maybe go to the above directory and try to push the two commits
which are only local so far? It would be great when you can give it a try!

Best,
Ralf

Am Di., 17. Juli 2018 um 16:23 Uhr schrieb Foivos Gypas <
notifications@github.com>:

**Comment by fgypas** [comment]
Hi @koljaLanger 

I added you and @ajgruber as admins in the project. Can you try to push again?
In case it's not working maybe you need to update your ssh key.

Let me know if it's working now.

Foivos

**Comment by koljaLanger** [comment]
It works now again! Hopefully, with the latest commit the issue is solved. I mark it as solved. Please reopen in case you still encounter problems.
